title: "Rozmówki Techno Logiczne"
description: "Luźny podcast o poważnych technologiach"
author:
  name: "Damian"
  url: "https://jakbadacdane.pl"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Custom variables
owner : "Rozmówki Techno Logiczne"
year : "2020"

google_analytics: "UA-158930420-1"
excerpt_separator: "<!--end_excerpt-->"

default_locale: "pl"
